version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 13.4.1 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme Cormorant 
          environment:
            SWIFT_VERSION: 4.0

  build: 
    macos:
      xcode: 13.4.1 # indicate your selected version of Xcode
    steps: 
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
          environment:
            SWIFT_VERSION: 4.0
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/Cormorant.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
          
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
